### ISSUE TITLE
Registration  - NPE

### ISSUE THREAD

**Issue by ber4444** [okta/okta-idx-android#109]
```
2021-11-29 13:01:32.125 7201-7232/com.okta.idx.android E/FormAction$proceed: An error occurred.
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
        at com.okta.idx.android.directauth.sdk.FormAction$proceedToRegister$1.invokeSuspend(FormAction.kt:320)
        at com.okta.idx.android.directauth.sdk.FormAction$proceedToRegister$1.invoke(Unknown Source:8)
        at com.okta.idx.android.directauth.sdk.FormAction$proceedToRegister$1.invoke(Unknown Source:4)
        at com.okta.idx.android.directauth.sdk.FormAction$ProceedData.invokeTransitionFactory(FormAction.kt:223)
        at com.okta.idx.android.directauth.sdk.FormAction$proceed$1.invokeSuspend(FormAction.kt:236)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by ber4444** [comment]
If could patch it via 
```
            val attributeList = newUserRegistrationResponse.formValues?.getOrNull(0)?.form?.value?.map {
                RegisterForm.Attribute(it.name, it.label)
            } ?: emptyList()
```
so now it is giving me a user friendly (but still cryptic) error: "The current flow is not supported. Please check your policy configuration."

Note that the Login flow works fine, only Registration has this issue.

**Comment by JayNewstrom** [comment]
Hi @ber4444 Can you share some information about how your org is configured? 

Have you set up an enrollment policy? 

If you want to send a PR, that would be better than only printing the error to the console.

**Comment by ber4444** [comment]
Our app is under Default Policy in Profile Enrollment Policies, is that insufficient?

**Comment by JayNewstrom** [comment]
Looks like you found it :) If you want to send a PR, that'd be cool, if not, I can make the change later. Let me know if you run into other issues.
